local M = {}

function M.highlight(color)
	return {
		ColorColumn = {
			fg = color.alt_black,
			bg = color.bg,
		},
		Conceal = { fg = color.alt_white },
		CurSearch = {
			fg = color.bg,
			bg = color.magenta,
			bold = true,
		},
		Cursor = { fg = color.black, bg = color.white },
		lCursor = { fg = color.black, bg = color.white },
		CursorIM = { fg = color.black, bg = color.white },
		CursorColumn = { bg = color.black },
		CursorLine = { bg = color.black },
		Directory = { bg = color.blue },
		DiffAdd = { bg = color.green, fg = color.alt_black },
		DiffChange = { bg = color.yellow, fg = color.alt_black },
		DiffDelete = { bg = color.red, fg = color.alt_black },
		DiffText = { fg = color.alt_blank },
		EndOfBuffer = { fg = color.alt_black, bg = color.bg },
		TermCursor = { fg = color.black, bg = color.white, reverse = false },
		TermCursorNC = { fg = color.black, reverse = false },
		ErrorMsg = { fg = color.red, bg = color.bg, bold = true },
		WinSeparator = { bg = color.black },
		Folded = { bg = color.bg, fg = color.alt_black },
		FoldColumn = { bg = color.black, fg = color.alt_white },
		SignColumn = { bg = color.bg, fg = color.alt_black },
		IncSearch = { bg = color.alt_blue, fg = color.alt_black },
		Substitute = { bg = color.alt_blue, fg = color.alt_black },
		LineNr = { fg = color.alt_white },
		CursorLineNr = { fg = color.alt_white, bold = true },
		MatchParen = { fg = color.alt_blue, bg = color.alt_black, bold = true },
		ModeMsg = { fg = color.fg, bg = color.bg, bold = true },
		MsgArea = { fg = color.fg, bg = color.bg },
		MsgSeparator = { fg = color.fg, bg = color.bg },
		MoreMsg = { fg = color.cyan },
		NonText = { fg = color.fg, bg = color.red },
		Normal = { fg = color.fg },
		NormalFloat = { bg = color.black },
		FloatBorder = { fg = color.alt_black },
		FloatTitle = { fg = color.alt_black },
		NormalNC = { fg = color.fg },
		Pmenu = { bg = color.black, fg = color.fg },
		PmenuSel = { bg = color.alt_black, fg = color.fg, bold = true},
		PmenuThumb = { bg = color.white },
		PmenuSbar = { bg = color.black },
		Question = { fg = color.blue },
		QuickFixLine = { bg = color.cyan },
		Search = { fg = color.magenta, bg = color.black },
		SpecialKey = { fg = color.magenta },
		SpellBad = { sp = color.red, undercurl = true },
		SpellCap = { sp = color.yellow, undercurl = true},
		SpellLocal = { sp = color.cyan, undercurl = true },
		SpellRare = { sp = color.magenta, undercurl = true },
		StatusLine = { bg = color.black, fg = color.fg },
		StatusLineNC = { bg = color.black, fg = color.alt_black },
		TabLine = { bg = color.black, fg = color.alt_white },
		TabLineFill = { bg = color.black},
		TabLineSel = { bg = color.alt_black, fg = color.white },
		Title = { fg = color.magenta },
		Visual = { bg = color.alt_black },
		VisualNOS = { bg = color.black },
		WarningMsg = { bg = color.bg, fg = color.red },
		Whitespace = { fg = color.white },
		WildMenu = { bg = color.alt_black, fg = color.fg, bold = true},
	}
end

return M
