local M = {}

function M.highlight(color)
	return {
		ColorColumn = {
			fg = color.alt_black,
			bg = color.bg,
		},
		Conceal = { fg = color.alt_white },
		CurSearch = {
			fg = color.bg,
			bg = color.magenta,
			bold = true,
		},
		Cursor = { fg = color.black, bg = color.white },
        CursorLine = { bg = color.alt_black},
		lCursor = { fg = color.black, bg = color.white },
		CursorIM = { fg = color.black, bg = color.white },
		CursorColumn = { bg = color.black },
		Directory = { fg = color.blue },
		DiffAdd = { bg = color.green, fg = color.alt_black },
		DiffChange = { bg = color.yellow, fg = color.alt_black },
		DiffDelete = { bg = color.red, fg = color.alt_black },
		DiffText = { fg = color.alt_blank },
		EndOfBuffer = { fg = color.alt_black, bg = color.bg },
		TermCursor = { fg = color.black, bg = color.white, reverse = false },
		TermCursorNC = { fg = color.black, reverse = false },
		ErrorMsg = { fg = color.red, bg = color.bg, bold = true },
		WinSeparator = { fg = color.alt_black, bg = color.black },
		Folded = { bg = color.bg, fg = color.alt_black },
		FoldColumn = { bg = color.black, fg = color.alt_white },
		SignColumn = { bg = color.bg, fg = color.alt_black },
		IncSearch = { bg = color.alt_blue, fg = color.alt_black },
		Substitute = { bg = color.alt_blue, fg = color.alt_black },
		LineNr = { fg = color.alt_fg },
		CursorLineNr = { bg = color.black, fg = color.alt_white, bold = true },
		MatchParen = { fg = color.alt_blue, bg = color.alt_black, bold = true },
		ModeMsg = { fg = color.fg, bg = color.bg, bold = true },
		MsgArea = { fg = color.fg, bg = color.bg },
		MsgSeparator = { fg = color.fg, bg = color.bg },
		MoreMsg = { fg = color.cyan },
		NonText = { fg = color.fg, bg = color.red },
		Normal = { fg = color.fg },
		NormalFloat = { bg = color.black },
		FloatBorder = { fg = color.alt_black },
		FloatTitle = { bg = color.bg, fg = color.alt_black },
		NormalNC = { fg = color.fg },
		Pmenu = { bg = color.black, fg = color.fg },
		PmenuSel = { bg = color.black, fg = color.fg, bold = true },
		PmenuThumb = { bg = color.white },
		PmenuSbar = { bg = color.black },
		Question = { fg = color.blue },
		QuickFixLine = { bg = color.cyan },
		Search = { fg = color.magenta, bg = color.black },
		SpecialKey = { fg = color.magenta },
		SpellBad = { sp = color.red, undercurl = true },
		SpellCap = { sp = color.yellow, undercurl = true },
		SpellLocal = { sp = color.cyan, undercurl = true },
		SpellRare = { sp = color.magenta, undercurl = true },
		StatusLine = { bg = color.black, fg = color.fg },
		StatusLineNC = { bg = color.black, fg = color.alt_black },
		TabLine = { bg = color.black, fg = color.alt_white },
		TabLineFill = { bg = color.bg },
		TabLineSel = { bg = color.black, fg = color.white },
		Title = { fg = color.magenta },
		Visual = { bg = color.alt_black },
		VisualNOS = { bg = color.black },
		WarningMsg = { bg = color.bg, fg = color.red },
		Whitespace = { fg = color.white },
		WildMenu = { bg = color.black, fg = color.fg, bold = true },
		Variable = { fg = color.white },
		String = { fg = color.alt_blue },
		Character = { fg = color.alt_green },
		Constant = { fg = color.white },
		Number = { fg = color.magenta },
		Boolean = { fg = color.magenta },
		Float = { fg = color.magenta },
		Identifier = { fg = color.blue },
		Function = { fg = color.alt_blue, bold = true },
		Operator = { fg = color.white },
		Type = { fg = color.white, bold = true },
		StorageClass = { fg = color.alt_blue },
		Structure = { fg = color.alt_blue },
		Typedef = { fg = color.alt_white },
		Keyword = { fg = color.alt_blue, bold = true },
		Statement = { fg = color.white },
		Conditional = { fg = color.alt_blue },
		Repeat = { fg = color.alt_blue },
		Label = { fg = color.white },
		Exception = { fg = color.alt_red },
		Include = { fg = color.alt_red },
		PreProc = { fg = color.white },
		Define = { fg = color.alt_red },
		Macro = { fg = color.blue },
		PreCondit = { fg = color.alt_cyan },
		Special = { fg = color.white },
		SpecialChar = { fg = color.alt_cyan },
		Tag = { fg = color.blue },
		Debug = { fg = color.alt_red },
		Delimiter = { fg = color.alt_white },
		SpecialComment = { fg = color.alt_cyan, italic = true },
		Comment = { fg = color.alt_black, italic = true },
		Underlined = { underline = true },
		Italic = { italic = true },
		Ignore = { fg = color.alt_black, bg = color.bg, bold = true },
		Todo = { fg = color.red, bold = true },
		Error = { fg = color.red, bg = color.bg, bold = true },
		NetrwCursorline = { bg = color.alt_black },
	}
end

-- HEllo

return M
